
name: .net cicd
on:
  push:
     branches:
       - master  
jobs:
   deploy:
      runs-on: self-hosted
      steps:
        - name: copy repository
          uses: actions/checkout@v4

        - name: copy from workspaces
          shell: pwsh
          run: |
            $source = "${{ github.workspace}}"
            $dest = "D:\SourceNet"
            Copy-Item -Path "$source" -Destination $dest -Recurse -Force
            Write-host " copy ok"

        - name: install dot net
          uses: actions/setup-dotnet@v4
          
        - name: restore nuget
          shell: pwsh
          run: |
            cd D:\SourceNet\SampleStore
            dotnet restore  

        - name: build project
          shell: pwsh
          run: |
               cd D:\SourceNet\SampleStore
               dotnet build --configuration Release "d:\SourceNet\SampleStore\Release"     

    