name: Build & Deploy .NET Project to IIS

on:
  push:
    branches:
      - main   # اجرا هنگام پوش روی main

jobs:
  deploy:
    runs-on: self-hosted   # ویندوز سرور با Runner شخصی

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy repository to deploy directory
        shell: pwsh
        run: |
          $src = "${{ github.workspace }}"
          $dst = "C:\deploy\myapp"
          if (Test-Path $dst) { Remove-Item $dst -Recurse -Force }
          Copy-Item -Path "$src" -Destination $dst -Recurse -Force

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Detect project automatically
        shell: pwsh
        run: |
          cd "C:\deploy\myapp"
          # جست‌وجوی .csproj عادی (به‌جز تست‌ها)
          $projects = Get-ChildItem -Path . -Recurse -Filter *.csproj | Where-Object {
              $_.FullName -notmatch '\\test|\\tests'
          }
          if (-not $projects) { throw "❌ هیچ فایل csproj پیدا نشد!" }

          # انتخاب اولین پروژه اجرایی
          $mainProject = $projects[0].FullName
          Write-Host "✅ Project detected => $mainProject"

          # ذخیره در فایل برای مراحل بعد
          Set-Content -Path "C:\deploy\myapp\selected_project.txt" -Value $mainProject

      - name: Restore NuGet packages
        shell: pwsh
        run: |
          $proj = Get-Content "C:\deploy\myapp\selected_project.txt"
          cd (Split-Path $proj)
          dotnet restore $proj
          if ($LASTEXITCODE -ne 0) { throw "Restore failed." }

      - name: Build project
        shell: pwsh
        run: |
          $proj = Get-Content "C:\deploy\myapp\selected_project.txt"
          $projDir = Split-Path $proj
          cd $projDir
          dotnet build --configuration Release $proj
          if ($LASTEXITCODE -ne 0) { throw "Build failed." }

      - name: Publish project
        shell: pwsh
        run: |
          $proj = Get-Content "C:\deploy\myapp\selected_project.txt"
          $projDir = Split-Path $proj
          $publishOut = "C:\deploy\myapp\publish"
          cd $projDir
          dotnet publish --configuration Release --output $publishOut $proj
          if ($LASTEXITCODE -ne 0) { throw "Publish failed." }

      - name: Deploy to IIS
        shell: pwsh
        run: |
          $publishPath = "C:\deploy\myapp\publish"
          $iisPath     = "C:\inetpub\wwwroot"
          $publishExists = Test-Path $publishPath
          $iisExists     = Test-Path $iisPath
          if ($publishExists -and $iisExists) {
              Copy-Item -Path "$publishPath\*" -Destination $iisPath -Recurse -Force
          } else {
              throw "Invalid path. Publish or IIS directory not found."
          }

      - name: Restart IIS
        shell: pwsh
        run: iisreset
